[package]
name = "shiTFTP"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.8.2"
clap = { version = "4.5.37", features = ["derive"] }
ctor = "0.4.1"
env_logger = "0.11.8"
hex = "0.4.3"
log = "0.4.27"
